project:
  type: website
  output-dir: docs

website:
  title: "WG6 Bioforest Analyses"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Analyses"
        menu:
          - text: "smoothing agb_growth"
            href: analyses/smooth_final_models.html

    right:
      - icon: github
        href: https://github.com/ericarievrs/WG6-Bioforest

format:
  html:
    theme: flatly
    toc: true
    toc-location: left
    code-fold: true
